// <auto-generated />
namespace username_Wines.DAL.WineMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Audi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Audi));
        
        string IMigrationMetadata.Id
        {
            get { return "201711231955409_Audi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
